// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  projectSidebar: [
    {
      "type": "html",
      "value": "<img src='/sysImg/projectLogo.png' alt='Alt text' />",
      "defaultStyle": true
    },
    {
      type: 'autogenerated',
      dirName: '.'
    }
  ],
};

export default sidebars;
